### ISSUE TITLE
train & eval question

### ISSUE THREAD

**Issue by germanjke** [MatanCohen1/Transformaly#1]
Hi Guys! 
I'm right that train & eval script using same data? 
So I can't use new test data just for evaluate my existing models?

**Comment by MatanCohen1** [comment]
Hi,
For training and testing, the scripts use the regular partitions of the datasets (CIFAR10/CIFAR100/...).
To support other datasets, even just for testing, you should implement it in the util functions "get_datasets_for_ViT" and "get_datasets". 
Good luck!

**Comment by germanjke** [comment]
I trained models on train dataset, but when i'm making eval on test dataset i have this error

Found input variables with inconsistent numbers of samples: [`lenght_of_test_dataset`, `lenght_of_train_dataset`]

So I can make  eval only on train data

I guess you saving some vectors to `npy` to roc_auc, and later, it's some miss match in case with datasets with different lenght

**Comment by MatanCohen1** [comment]
It may be the case, although the current evaluation uses test data from each dataset of course. This is probably another change that you should make in order to support the evaluation of different datasets. You can attach the full error and I'll try to assist.
